function CodeDefine() { 
this.def = new Array();
this.def["ert_main.cpp:rtObj"] = {file: "ert_main_cpp.html",line:29,type:"var"};
this.def["stopRequested"] = {file: "ert_main_cpp.html",line:38,type:"var"};
this.def["runModel"] = {file: "ert_main_cpp.html",line:39,type:"var"};
this.def["stopSem"] = {file: "ert_main_cpp.html",line:40,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_cpp.html",line:41,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_cpp.html",line:42,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_cpp.html",line:43,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_cpp.html",line:44,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_cpp.html",line:45,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_cpp.html",line:46,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_cpp.html",line:63,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_cpp.html",line:70,type:"fcn"};
this.def["main"] = {file: "ert_main_cpp.html",line:90,type:"fcn"};
this.def["step"] = {file: "try1_cpp.html",line:23,type:"fcn"};
this.def["initialize"] = {file: "try1_cpp.html",line:39,type:"fcn"};
this.def["terminate"] = {file: "try1_cpp.html",line:52,type:"fcn"};
this.def["getRTM"] = {file: "try1_cpp.html",line:70,type:"fcn"};
this.def["ExtU"] = {file: "try1_h.html",line:44,type:"type"};
this.def["ExtY"] = {file: "try1_h.html",line:50,type:"type"};
this.def["rtU"] = {file: "try1_h.html",line:72,type:"var"};
this.def["P"] = {file: "try1_types_h.html",line:24,type:"type"};
this.def["RT_MODEL"] = {file: "try1_types_h.html",line:27,type:"type"};
this.def["rtP"] = {file: "try1_data_cpp.html",line:23,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:85,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:90,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:137,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:144,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:151,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:172,type:"type"};
this.def["MW_Pyserver_control.c:exePath"] = {file: "MW_Pyserver_control_c.html",line:21,type:"var"};
this.def["MW_Pyserver_control.c:pyserverLoc"] = {file: "MW_Pyserver_control_c.html",line:22,type:"var"};
this.def["MW_getDefines"] = {file: "MW_Pyserver_control_c.html",line:24,type:"fcn"};
this.def["MW_killPyserver"] = {file: "MW_Pyserver_control_c.html",line:41,type:"fcn"};
this.def["MW_launchPyserver"] = {file: "MW_Pyserver_control_c.html",line:52,type:"fcn"};
this.def["MW_execmd"] = {file: "MW_Pyserver_control_c.html",line:64,type:"fcn"};
this.def["mwRaspiInit"] = {file: "MW_raspi_init_c.html",line:8,type:"fcn"};
this.def["mwRaspiTerminate"] = {file: "MW_raspi_init_c.html",line:24,type:"fcn"};
this.def["reportOverrun"] = {file: "MW_raspi_init_c.html",line:35,type:"fcn"};
this.def["MW_AsyncTaskCodeGenInfo_Type"] = {file: "linuxinitialize_cpp.html",line:28,type:"type"};
this.def["linuxinitialize.cpp:MW_TSKMGR_EVENT_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:32,type:"var"};
this.def["mw_setAsyncTaskCodeGenInfo"] = {file: "linuxinitialize_cpp.html",line:34,type:"fcn"};
this.def["baseRateInfo_t"] = {file: "linuxinitialize_cpp.html",line:52,type:"type"};
this.def["baseTimerThread"] = {file: "linuxinitialize_cpp.html",line:54,type:"var"};
this.def["attr"] = {file: "linuxinitialize_cpp.html",line:56,type:"var"};
this.def["info"] = {file: "linuxinitialize_cpp.html",line:57,type:"var"};
this.def["sp"] = {file: "linuxinitialize_cpp.html",line:58,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:73,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:74,type:"var"};
this.def["MW_NUMBER_TIMER_DRIVEN_TASKS"] = {file: "linuxinitialize_cpp.html",line:75,type:"var"};
this.def["mw_CreateArmedTimer"] = {file: "linuxinitialize_cpp.html",line:78,type:"fcn"};
this.def["mw_init_timerTaskSem"] = {file: "linuxinitialize_cpp.html",line:105,type:"fcn"};
this.def["mw_CreateUnarmedTimer"] = {file: "linuxinitialize_cpp.html",line:112,type:"fcn"};
this.def["mw_ArmTimer"] = {file: "linuxinitialize_cpp.html",line:139,type:"fcn"};
this.def["mw_WaitForTimerEvent"] = {file: "linuxinitialize_cpp.html",line:164,type:"fcn"};
this.def["mw_WaitForTimerEventCatchup"] = {file: "linuxinitialize_cpp.html",line:180,type:"fcn"};
this.def["baseTimerTask"] = {file: "linuxinitialize_cpp.html",line:221,type:"fcn"};
this.def["schedulerTask"] = {file: "linuxinitialize_cpp.html",line:236,type:"fcn"};
this.def["my_sem_wait"] = {file: "linuxinitialize_cpp.html",line:258,type:"fcn"};
this.def["linuxinitialize.cpp:setThreadPriority"] = {file: "linuxinitialize_cpp.html",line:268,type:"fcn"};
this.def["mw_CreateTask"] = {file: "linuxinitialize_cpp.html",line:283,type:"fcn"};
this.def["myAddBlockForThisEvent"] = {file: "linuxinitialize_cpp.html",line:342,type:"fcn"};
this.def["myAddHandlerForThisEvent"] = {file: "linuxinitialize_cpp.html",line:353,type:"fcn"};
this.def["myRestoreDefaultHandlerForThisEvent"] = {file: "linuxinitialize_cpp.html",line:369,type:"fcn"};
this.def["myRTOSInit"] = {file: "linuxinitialize_cpp.html",line:384,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["try1_cpp.html"] = "../try1.cpp";
	this.html2Root["try1_cpp.html"] = "try1_cpp.html";
	this.html2SrcPath["try1_h.html"] = "../try1.h";
	this.html2Root["try1_h.html"] = "try1_h.html";
	this.html2SrcPath["try1_private_h.html"] = "../try1_private.h";
	this.html2Root["try1_private_h.html"] = "try1_private_h.html";
	this.html2SrcPath["try1_types_h.html"] = "../try1_types.h";
	this.html2Root["try1_types_h.html"] = "try1_types_h.html";
	this.html2SrcPath["try1_data_cpp.html"] = "../try1_data.cpp";
	this.html2Root["try1_data_cpp.html"] = "try1_data_cpp.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_Pyserver_control_c.html"] = "../../../../../../../../../../../../ProgramData/MATLAB/SupportPackages/R2019b/toolbox/realtime/targets/raspi/src/periphs/MW_Pyserver_control.c";
	this.html2Root["MW_Pyserver_control_c.html"] = "MW_Pyserver_control_c.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_raspi_init_c.html"] = "../../../../../../../../../../../../ProgramData/MATLAB/SupportPackages/R2019b/toolbox/realtime/targets/raspi/server/MW_raspi_init.c";
	this.html2Root["MW_raspi_init_c.html"] = "MW_raspi_init_c.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["linuxinitialize_cpp.html"] = "../../../../../../../../../../../../Program Files/MATLAB/R2019b/toolbox/target/codertarget/rtos/src/linuxinitialize.cpp";
	this.html2Root["linuxinitialize_cpp.html"] = "linuxinitialize_cpp.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","try1_cpp.html","try1_h.html","try1_private_h.html","try1_types_h.html","try1_data_cpp.html","rtwtypes_h.html","rtmodel_h.html","MW_Pyserver_control_c.html","MW_custom_RTOS_header_h.html","MW_raspi_init_c.html","MW_target_hardware_resources_h.html","linuxinitialize_cpp.html"];
